In [122]:
import numpy as np 
import pandas as pd

In [123]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [124]:
df1 = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [125]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [126]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    for l in range(1, L):
        parameters['W' + str(l)]= np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)]= np.zeros((layer_dims[l],1))
    return parameters  

In [127]:
def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    return A

In [128]:
def linear_forwardn(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    A = sigmoid(Z)
    return A

In [129]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    return Z

In [130]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev

In [131]:
# Forward Prop
def L_layer_forwardn(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forwardn(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev

In [132]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [133]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [134]:
X=df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y= df[['placed']].values[0][0]

X1=df1[['cgpa', 'profile_score']].values[0].reshape(2,1)
y1= df1[['placed']].values[0][0]

parameters= initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X,parameters)
y_hat1,A11 = L_layer_forwardn(X1,parameters)

In [135]:
parameters= initialize_parameters([2,2,1])

In [136]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [137]:
y_hat,A1

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [138]:
y_hat1,A11

(array([[0.54150519]]),
 array([[0.83201839],
        [0.83201839]]))

In [139]:
parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.2663555135529325
Epoch -  2 Loss -  0.2348080560708281
Epoch -  3 Loss -  0.23476151967276615
Epoch -  4 Loss -  0.23471521177139515
Epoch -  5 Loss -  0.23466913088970426


{'W1': array([[0.09969652, 0.0997215 ],
        [0.09969638, 0.09972133]]),
 'b1': array([[-3.63841483e-05],
        [-3.64031068e-05]]),
 'W2': array([[0.1004557 ],
        [0.10045577]]),
 'b2': array([[0.10042569]])}

In [140]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7272094688603609
Epoch -  2 Loss -  0.6591359478931171
Epoch -  3 Loss -  0.6590477313626301
Epoch -  4 Loss -  0.6589599674625288
Epoch -  5 Loss -  0.6588726531338515
Epoch -  6 Loss -  0.6587857853429255
Epoch -  7 Loss -  0.6586993610811188
Epoch -  8 Loss -  0.6586133773645956
Epoch -  9 Loss -  0.6585278312340734
Epoch -  10 Loss -  0.6584427197545836
Epoch -  11 Loss -  0.6583580400152345
Epoch -  12 Loss -  0.6582737891289767
Epoch -  13 Loss -  0.6581899642323725
Epoch -  14 Loss -  0.6581065624853655
Epoch -  15 Loss -  0.6580235810710551
Epoch -  16 Loss -  0.6579410171954725
Epoch -  17 Loss -  0.6578588680873589
Epoch -  18 Loss -  0.6577771309979471
Epoch -  19 Loss -  0.6576958032007443
Epoch -  20 Loss -  0.6576148819913188
Epoch -  21 Loss -  0.6575343646870879
Epoch -  22 Loss -  0.6574542486271084
Epoch -  23 Loss -  0.6573745311718705
Epoch -  24 Loss -  0.6572952097030917
Epoch -  25 Loss -  0.6572162816235155
Epoch -  26 Loss -  0.657137744356

{'W1': array([[0.09714987, 0.09740318],
        [0.09713711, 0.09739131]]),
 'b1': array([[-0.0003413 ],
        [-0.00034276]]),
 'W2': array([[0.10424659],
        [0.10425213]]),
 'b2': array([[0.10422142]])}